// This file is auto-generated by @hey-api/openapi-ts

import { type Options as ClientOptions, type TDataShape, type Client, urlSearchParamsBodySerializer } from './client/index.js';
import type { GetRefundsData, GetRefundsResponses, GetRefundsErrors, PostRefundsData, PostRefundsResponses, PostRefundsErrors, GetRefundsRefundData, GetRefundsRefundResponses, GetRefundsRefundErrors, PostRefundsRefundData, PostRefundsRefundResponses, PostRefundsRefundErrors, PostRefundsRefundCancelData, PostRefundsRefundCancelResponses, PostRefundsRefundCancelErrors } from './types.gen.js';
import { client as _heyApiClient } from './client.gen.js';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * List all refunds
 * <p>Returns a list of all refunds you created. We return the refunds in sorted order, with the most recent refunds appearing first. The 10 most recent refunds are always available by default on the Charge object.</p>
 */
export const getRefunds = <ThrowOnError extends boolean = false>(options?: Options<GetRefundsData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetRefundsResponses, GetRefundsErrors, ThrowOnError>({
        ...urlSearchParamsBodySerializer,
        querySerializer: {
            array: {
                explode: false,
                style: 'form'
            }
        },
        security: [
            {
                scheme: 'basic',
                type: 'http'
            },
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/v1/refunds',
        ...options,
        headers: {
            'Content-Type': 'application/x-www-form-urlencoded',
            ...options?.headers
        }
    });
};

/**
 * Create a refund
 * <p>When you create a new refund, you must specify a Charge or a PaymentIntent object on which to create it.</p>
 *
 * <p>Creating a new refund will refund a charge that has previously been created but not yet refunded.
 * Funds will be refunded to the credit or debit card that was originally charged.</p>
 *
 * <p>You can optionally refund only part of a charge.
 * You can do so multiple times, until the entire charge has been refunded.</p>
 *
 * <p>Once entirely refunded, a charge can’t be refunded again.
 * This method will raise an error when called on an already-refunded charge,
 * or when trying to refund more money than is left on a charge.</p>
 */
export const postRefunds = <ThrowOnError extends boolean = false>(options?: Options<PostRefundsData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<PostRefundsResponses, PostRefundsErrors, ThrowOnError>({
        ...urlSearchParamsBodySerializer,
        security: [
            {
                scheme: 'basic',
                type: 'http'
            },
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/v1/refunds',
        ...options,
        headers: {
            'Content-Type': 'application/x-www-form-urlencoded',
            ...options?.headers
        }
    });
};

/**
 * Retrieve a refund
 * <p>Retrieves the details of an existing refund.</p>
 */
export const getRefundsRefund = <ThrowOnError extends boolean = false>(options: Options<GetRefundsRefundData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetRefundsRefundResponses, GetRefundsRefundErrors, ThrowOnError>({
        ...urlSearchParamsBodySerializer,
        querySerializer: {
            array: {
                explode: false,
                style: 'form'
            }
        },
        security: [
            {
                scheme: 'basic',
                type: 'http'
            },
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/v1/refunds/{refund}',
        ...options,
        headers: {
            'Content-Type': 'application/x-www-form-urlencoded',
            ...options.headers
        }
    });
};

/**
 * Update a refund
 * <p>Updates the refund that you specify by setting the values of the passed parameters. Any parameters that you don’t provide remain unchanged.</p>
 *
 * <p>This request only accepts <code>metadata</code> as an argument.</p>
 */
export const postRefundsRefund = <ThrowOnError extends boolean = false>(options: Options<PostRefundsRefundData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<PostRefundsRefundResponses, PostRefundsRefundErrors, ThrowOnError>({
        ...urlSearchParamsBodySerializer,
        security: [
            {
                scheme: 'basic',
                type: 'http'
            },
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/v1/refunds/{refund}',
        ...options,
        headers: {
            'Content-Type': 'application/x-www-form-urlencoded',
            ...options.headers
        }
    });
};

/**
 * Cancel a refund
 * <p>Cancels a refund with a status of <code>requires_action</code>.</p>
 *
 * <p>You can’t cancel refunds in other states. Only refunds for payment methods that require customer action can enter the <code>requires_action</code> state.</p>
 */
export const postRefundsRefundCancel = <ThrowOnError extends boolean = false>(options: Options<PostRefundsRefundCancelData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<PostRefundsRefundCancelResponses, PostRefundsRefundCancelErrors, ThrowOnError>({
        ...urlSearchParamsBodySerializer,
        security: [
            {
                scheme: 'basic',
                type: 'http'
            },
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/v1/refunds/{refund}/cancel',
        ...options,
        headers: {
            'Content-Type': 'application/x-www-form-urlencoded',
            ...options.headers
        }
    });
};