import fs from "node:fs";
import path from "node:path";
import { isObject } from "./json.js";
import { projectPaths } from "./paths.js";

export interface DriftIssue {
  path: string;
  expected: string;
  received: string;
}

export interface DriftEntry {
  time: string;
  operation: string;
  issues: DriftIssue[];
}

export function readDriftLog(cwd: string): DriftEntry[] {
  const file = projectPaths(cwd).driftLog;
  if (!fs.existsSync(file)) return [];
  return fs
    .readFileSync(file, "utf8")
    .split("\n")
    .filter(Boolean)
    .map((line) => JSON.parse(line) as DriftEntry);
}

export function writeDriftRuntime(
  outDir: string,
  doc: Record<string, unknown>,
  operations: string[],
): string {
  const schemas = operations
    .map((operation) => {
      const schema = responseSchema(doc, operation);
      if (!schema) return undefined;
      return `  ${JSON.stringify(operation)}: ${zodExpr(schema, doc, new Set())},`;
    })
    .filter(Boolean)
    .join("\n");
  const routes = operations
    .map((operation) => {
      const [method, opPath] = operation.split(" ");
      if (!method || !opPath) return undefined;
      return `  { method: ${JSON.stringify(method)}, path: ${JSON.stringify(opPath)} },`;
    })
    .filter(Boolean)
    .join("\n");
  const source = `// Generated by apiweld. Report-only response checks. Do not edit.
import { appendFileSync, mkdirSync } from "node:fs";
import { dirname } from "node:path";
import { z } from "zod";

const logPath = process.env.APIWELD_DRIFT_LOG ?? ".apiweld/drift.log.jsonl";

export const responseSchemas: Record<string, z.ZodType> = {
${schemas}
};

const routes: Array<{ method: string; path: string }> = [
${routes}
];

function receivedType(value: unknown, segments: PropertyKey[]): string {
  let current: unknown = value;
  for (const segment of segments) {
    if (current == null || typeof current !== "object") return "missing";
    current = (current as Record<PropertyKey, unknown>)[segment];
  }
  if (current === null) return "null";
  if (Array.isArray(current)) return "array";
  return typeof current;
}

export function reportResponse(operation: string, data: unknown): void {
  const schema = responseSchemas[operation];
  if (!schema) return;
  const parsed = schema.safeParse(data);
  if (parsed.success) return;
  const issues = parsed.error.issues.map((issue) => ({
    path: issue.path.map(String).join("."),
    expected: "expected" in issue && typeof issue.expected === "string" ? issue.expected : issue.code,
    received: receivedType(data, issue.path),
  }));
  const line = JSON.stringify({ time: new Date().toISOString(), operation, issues });
  mkdirSync(dirname(logPath), { recursive: true });
  appendFileSync(logPath, line + "\\n");
}

function matches(template: string, pathname: string): boolean {
  const expression = new RegExp("^" + template.replace(/\\{[^}]+\\}/g, "[^/]+") + "$");
  return expression.test(pathname);
}

export async function reportingFetch(input: RequestInfo | URL, init?: RequestInit): Promise<Response> {
  const response = await fetch(input, init);
  const method = (init?.method ?? "GET").toUpperCase();
  const pathname = new URL(typeof input === "string" ? input : input instanceof URL ? input : input.url, "http://local").pathname;
  const route = routes.find((item) => item.method === method && matches(item.path, pathname));
  if (!route) return response;
  try {
    reportResponse(method + " " + route.path, await response.clone().json());
  } catch {
    return response;
  }
  return response;
}
`;
  const file = path.join(outDir, "apiweld-drift.ts");
  fs.mkdirSync(outDir, { recursive: true });
  fs.writeFileSync(file, source);
  return file;
}

function responseSchema(doc: Record<string, unknown>, operation: string): unknown {
  const [method, opPath] = operation.split(" ");
  if (!method || !opPath || !isObject(doc.paths)) return undefined;
  const item = doc.paths[opPath];
  if (!isObject(item)) return undefined;
  const op = item[method.toLowerCase()];
  if (!isObject(op) || !isObject(op.responses)) return undefined;
  const code = ["200", "201", "202"].find((status) => isObject(op.responses) && op.responses[status]);
  const response = code ? op.responses[code] : undefined;
  if (!isObject(response) || !isObject(response.content)) return undefined;
  const json = response.content["application/json"];
  return isObject(json) ? json.schema : undefined;
}

function zodExpr(schema: unknown, doc: Record<string, unknown>, stack: Set<string>): string {
  if (!isObject(schema)) return "z.unknown()";
  if (typeof schema.$ref === "string") {
    if (stack.has(schema.$ref)) return "z.unknown()";
    stack.add(schema.$ref);
    const resolved = resolveRef(doc, schema.$ref);
    const expr = zodExpr(resolved, doc, stack);
    stack.delete(schema.$ref);
    return expr;
  }
  let expr = "z.unknown()";
  if (Array.isArray(schema.enum) && schema.enum.every((item) => typeof item === "string")) {
    expr = `z.enum([${schema.enum.map((item) => JSON.stringify(item)).join(", ")}])`;
  } else if (schema.type === "string") expr = "z.string()";
  else if (schema.type === "integer" || schema.type === "number") expr = "z.number()";
  else if (schema.type === "boolean") expr = "z.boolean()";
  else if (schema.type === "array") expr = `z.array(${zodExpr(schema.items, doc, stack)})`;
  else if (schema.type === "object" || schema.properties || schema.additionalProperties) {
    if (schema.additionalProperties && !schema.properties) {
      const inner = schema.additionalProperties === true ? "z.unknown()" : zodExpr(schema.additionalProperties, doc, stack);
      expr = `z.record(z.string(), ${inner})`;
    } else {
      const properties = isObject(schema.properties) ? schema.properties : {};
      const required = new Set(Array.isArray(schema.required) ? schema.required.map(String) : []);
      const fields = Object.keys(properties).map((name) => {
        const child = zodExpr(properties[name], doc, stack);
        const wrapped = required.has(name) ? child : `${child}.optional()`;
        return `${JSON.stringify(name)}: ${wrapped}`;
      });
      expr = `z.object({ ${fields.join(", ")} }).passthrough()`;
    }
  }
  if (schema.nullable === true) expr = `${expr}.nullable()`;
  return expr;
}

function resolveRef(doc: Record<string, unknown>, ref: string): unknown {
  const match = ref.match(/^#\/(.+)$/);
  if (!match?.[1]) return undefined;
  let current: unknown = doc;
  for (const part of match[1].split("/")) {
    if (!isObject(current)) return undefined;
    current = current[decodeURIComponent(part)];
  }
  return current;
}
